config/routes.rb
Rails.application.routes.draw do
  # Likes and Matches routes for authenticated users
  resources :likes, only: [ :index ]
  resources :matches, only: [ :index ]

  # notifications, profile and settings routes for authenticated users
  resources :notifications, only: [ :index ]
  resource :profile, only: [ :show, :edit, :update ]
  resource :settings, only: [ :edit, :update ]

  # Upgrade route
  resources :upgrades, only: [ :index ] do
    collection do
      get "success"
    end
  end

  # Dashboard route
  resource :dashboard, only: [ :show ]

  devise_for :users

  # Dashboard as the root for authenticated users
  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  # Root for non-authenticated users
  root to: "home#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-400 text-black mt-6">
  <p class="w-full text-center mx-auto px-4 py-6">© <%= Time.now.year %> fmanimashaun development. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-white" data-controller="mobile-menu"> 
  <div class="mx-auto max-w-7xl px-4 py-4 sm:py-6 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center">

      <div class="flex items-center space-x-4">
        <%= link_to root_path do %>
          <div class="flex items-center space-x-1.5 sm:space-x-2">
            <%= inline_svg "logo.svg", class: "h-10 sm:h-12 w-auto" %>
            <%= inline_svg "logo_text.svg", class: "hidden xl:block h-3 sm:h-3.5 w-auto" %>
          </div>
        <% end %>
      </div>

      <nav>
        <div> 
          <% if user_signed_in? %>
            <div class="flex items-center space-x-4">
              <div class="hidden lg:flex items-center space-x-8 xl:space-x-12">
                <div class="space-x-2 flex items-center xl:space-x-4"> 
                  <%= link_to edit_settings_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-200 focus:outline-none" do %>
                    <%= inline_svg "Filter.svg", class: "h-5 w-5 xl:h-7 xl:w-7" %> 
                  <% end %>
                  <%= link_to notifications_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-200 focus:outline-none" do %>
                    <%= inline_svg "Notification.svg", class: "h-5 w-5 xl:h-7 xl:w-7" %>
                  <% end %>
                  <%= link_to profile_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-200 focus:outline-none" do %>
                    <%= inline_svg "Profile.svg", class: "h-5 w-5 xl:h-7 xl:w-7" %>
                  <% end %>
                </div>
  
                <div class="flex items-center space-x-1 text-base xl:text-lg">
                  <span>Membership Status:</span>
                  <%= inline_svg 'Star.svg', class: 'w-5 h-5' %>
                  <strong class="font-bold">
                    <%= current_user.membership %> 
                  </strong>
                </div>
  
                <%= link_to "Upgrade Account", upgrades_path, class: "bg-black text-white py-3 px-8 rounded-lg" %>
              </div>
  
              <button 
                class="lg:hidden" 
                aria-label="Toggle mobile menu" 
                aria-expanded="false"
                data-action="mobile-menu#toggle" 
                data-mobile-menu-target="button"
              >
                <%= inline_svg "hamburger.svg", class: "h-6 w-6" %>
              </button>
            </div>
          <% else %>
            <div class="flex items-center space-x-4">
              <%= link_to "Log in", new_user_session_path, class: "hidden md:block text-base sm:text-lg font-bold" %>
  
              <button 
                class="md:hidden" 
                aria-label="Toggle mobile menu" 
                aria-expanded="false"
                data-action="mobile-menu#toggle" 
                data-mobile-menu-target="button"
              >
                <%= inline_svg "hamburger.svg", class: "h-6 w-6" %>
              </button>
            </div>
          <% end %>
        </div>
      </nav>
    </div>
  </div>

  <div 
    class="lg:hidden fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 transform -translate-x-full transition-transform duration-300 ease-in-out" 
    id="mobile-menu" 
    aria-hidden="true"
    data-mobile-menu-target="menu"
  >
    <div class="w-72 h-full bg-white p-4 relative"> 
      <div class="flex justify-between items-center">
        <%= link_to root_path do %>
          <div class="flex items-center space-x-1.5 sm:space-x-2">
            <%= inline_svg "logo.svg", class: "h-10 sm:h-12 w-auto" %>
            <%= inline_svg "logo_text.svg", class: "block h-3 sm:h-3.5 w-auto" %>
          </div>
        <% end %>

        <button 
          class="text-gray-600 absolute top-4 right-4"  
          aria-label="Close menu" 
          data-action="mobile-menu#close"
        >
          <%= inline_svg "Close.svg", class: "h-5 w-5" %>
        </button>
      </div>

      <ul class="mt-6 space-y-4">
        <% if user_signed_in? %>
          <li><%= link_to "Settings", edit_settings_path, class: "text-gray-800 hover:text-gray-600" %></li>
        <% end %>
      </ul>

      <div class="absolute flex flex-col bottom-0 left-0 w-full p-4 space-y-4">
        <% if user_signed_in? %>
          <div class="flex items-center space-x-1 text-base xl:text-lg">
            <span>Membership Status:</span>
            <%= inline_svg 'Star.svg', class: 'w-5 h-5' %>
            <strong class="font-bold">
              <%= current_user.membership %> 
            </strong>
          </div>
          <%= link_to "Upgrade Account", upgrades_path, class: "bg-black text-white py-3 px-8 rounded-lg" %>
          <div class="w-full h-px bg-gray-300 my-4"></div> 
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-base sm:text-lg font-bold" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "text-base sm:text-lg font-bold" %>
        <% end %>
      </div>


    </div>  
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="hidden md:flex text-white px-4 py-5">
  <ul class="space-y-5 w-full">
    <li class="<%= current_page?(root_path) ? 'bg-red-500 text-white' : 'text-black' %> rounded-lg w-full px-2 xl:px-4 py-2">
      <%= link_to root_path, class: "flex items-center space-x-6" do %>
        <% if current_page?(root_path) %>
          <%= inline_svg "Send-white.svg", class: "h-5 w-5" %>
        <% else %>
          <%= inline_svg "Send-black.svg", class: "h-5 w-5" %>
        <% end %>
        <span class="hidden xl:block">Online Now</span>
      <% end %>
    </li>

    <li class="<%= current_page?(likes_path) ? 'bg-red-500 text-white' : 'text-black' %> rounded-lg w-full px-2 xl:px-4 py-2">
       <%= link_to likes_path, class: "flex items-center space-x-6" do %>
        <% if current_page?(likes_path)%>
          <%= inline_svg "Likes-white.svg", class: "h-5 w-5" %>
        <% else %>
          <%= inline_svg "Likes-black.svg", class: "h-5 w-5" %>
        <% end %>
        <span class="hidden xl:block">Likes</span>
      <% end %>
    </li>

    <li class="<%= current_page?(matches_path) ? 'bg-red-500 text-white' : 'text-black' %> rounded-lg w-full px-2 xl:px-4 py-2">
      <%= link_to matches_path, class: "flex items-center space-x-6" do %>
        <% if current_page?(matches_path)%>
          <%= inline_svg "Match-white.svg", class: "h-5 w-5" %>
        <% else %>
          <%= inline_svg "Match-black.svg", class: "h-5 w-5" %>
        <% end %>
        <span class="hidden xl:block">Matches</span>
      <% end %>
    </li>

    <li class="<%= current_page?(edit_settings_path) ? 'bg-red-500 text-white' : 'text-black' %> rounded-lg w-full px-2 xl:px-4 py-2">
     <%= link_to edit_settings_path, class: "flex items-center space-x-6" do %>
        <% if current_page?(edit_settings_path) %>
          <%= inline_svg "Setting-white.svg", class: "h-5 w-5" %>
        <% else %>
          <%= inline_svg "Setting-black.svg", class: "h-5 w-5" %>
        <% end %>
        <span class="hidden xl:block">Settings</span>
      <% end %>
    </li>
  
    <li class="<%= current_page?(upgrades_path) ? 'bg-red-500 text-white' : 'text-black' %> hidden rounded-lg w-full px-2 xl:px-4 py-2">
      <%= link_to "Upgrade", upgrades_path, class: "" %>
    </li>
    <li class="<%= current_page?(destroy_user_session_path) ? 'bg-red-500 text-white' : 'text-black' %> hidden rounded-lg w-full px-2 xl:px-4 py-2">
      <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "" %>
    </li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= content_for(:title) || "Joymatcher Web" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <!-- Add Google Fonts link for Montserrat -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">


  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body class="h-screen m-0 grid grid-rows-[auto_1fr]">
  <%= render "layouts/header" %>

  <div class="w-full max-w-7xl mx-auto grid grid-cols-1 xl:grid-cols-[224px_1fr] md:grid-cols-[68px_1fr] overflow-hidden gap-8 md:gap-14 mt-6">
    <% if user_signed_in? %>
      <%= render "layouts/sidebar" %>
    <% end %>

    <main class="bg-white text-black overflow-y-scroll scrollbar-hide">
      <%= yield %>
    </main>
  </div>

</body>

</html>